### ISSUE TITLE
New base extension available

### ISSUE THREAD

**Issue by jamestomasino** [knod/read_plugin#104]
Hi @knod -
It looks like you've done a lot of work building off of Read over the years. I just wanted to let you know that the Read plugin itself is going to partially stop working as Mercury drops their parsing API. I had an opportunity to update it to something better and rather than keep the old architecture I built an entirely new extension using the web extensions API so that it supports both Chrome and Firefox.

https://github.com/jamestomasino/stutter

This is the new extension. It's working on both browsers though I still have plenty of planned updates for it. I thight it might be useful to you though. It's got a much better build system with isolated code for the background, content, and options sections. It's all webpack enabled with ES6 and scss. It should be much easier to extend and fork.

Cheers,
tomasino

**Comment by knod** [comment]
Thanks, that's really useful to know. I'll keep it in mind moving forward 👍
