### ISSUE TITLE
Remove [11] things by default and allow the user to bring them back temporarily

### ISSUE THREAD

**Issue by synapse25** [knod/read_plugin#21]
Remove [11] things by default and allow the user to bring them back temporarily

**Comment by knod** [comment]
The [11] refers to things like footnote references. The fix for this is going to be to remove all `<sup>` (superscript) tags from the text before reading it. It my have unfortunate consequences, so the ability to bring them back if you want them could help improve that experience.

**Comment by knod** [comment]
Removed with the <sup> tag now. I'm sure I closed this...
