### ISSUE TITLE
read whole page does not work in this page

### ISSUE THREAD

**Issue by synapse25** [knod/read_plugin#77]
https://www.theguardian.com/commentisfree/2017/jan/24/panama-papers-media-investigation-next-donald-trump-hold-accountable

**Comment by knod** [comment]
This page seems to be working for me. Did you wait long enough before pressing play?

**Comment by knod** [comment]
Of course, it's not reading the right stuff, but that's a different type of issue than it not working at all.

**Comment by knod** [comment]
This was tested in plain Chrome and seemed to work if the page was given sufficient time to load. The original environment of the error was Chromium and this is being moved to issue #83.
