### ISSUE TITLE
read whole page not working here

### ISSUE THREAD

**Issue by synapse25** [knod/read_plugin#80]
http://www.koutipandoras.gr/article/tsipras-oi-praikophmaties-den-einai-eyprosdektoi-alla-h-ellada-einai-kratos-dikaioy

**Comment by synapse25** [comment]
http://onlyjob.blogspot.com.cy/2011/03/perl5-python-ruby-php-c-c-lua-tcl.html

here too

**Comment by synapse25** [comment]
http://notebook.kulchenko.com/programming/lua-good-different-bad-and-ugly-parts

here too

**Comment by knod** [comment]
Issues moved to categories
